<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div5div4iframe1_c-x9j2mliy5o8z</name>
   <tag></tag>
   <elementGuidId>e1786ff7-3b54-4c39-9d49-8ab84edc86d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-x9j2mliy5o8z']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-x9j2mliy5o8z&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5dfd9fc9-57bf-431c-8c24-c52c1b174308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>masa berlaku tantangan recaptcha akan berakhir dalam dua menit</value>
      <webElementGuid>b4021611-fa36-42f1-86a6-d2f0ae2e31d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=zmiYzsHi8INTJBWt2QZC9aM5&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR</value>
      <webElementGuid>e55fbf64-ad40-4703-abe1-ff444101d1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-x9j2mliy5o8z</value>
      <webElementGuid>81ef2f81-3e80-497c-95f2-8d88844ed15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1dd02e2c-985e-4a9c-b3a4-394e76561464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a9598938-ea2a-4f3c-8d15-ad116956e114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>7391fc52-5419-46b5-acb3-9a877f3f6ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[5]/div[4]/iframe[1]</value>
      <webElementGuid>df18a56e-b78a-4b41-9d6e-31dcc7aa65c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-x9j2mliy5o8z']</value>
      <webElementGuid>b4d0219b-8c0f-4bd1-bc76-2b73ae4dc650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>dd42be19-faa2-4eec-aa1a-af36534b6988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'masa berlaku tantangan recaptcha akan berakhir dalam dua menit' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=zmiYzsHi8INTJBWt2QZC9aM5&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR' and @name = 'c-x9j2mliy5o8z']</value>
      <webElementGuid>1f989c7e-0c17-4261-add4-ef65ebcc5f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
