<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_perahu_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>cfb65157-efd2-4501-a8ab-aecb5909841c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>228f5bec-64d7-42ba-b6a2-8faeb775ef8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c54fa2af-f58f-48d1-88fd-49c61c031d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukzhxCtW-Se7DGWr83Sfmu0PubP8UHTdl_dIt0loTqwUQMIJDUggfSFvkquMH4TSt3ZFTACbiIagkArZi6CPqoG0AhU68lW4pvBHu8aM3-fmB0K4oIn7gLF7KKi2YhF7TiaT8zjVt2lslQl8-H97oFcTd9x13r1YYzt7CRp-RxKgFuSpDl2b52KwM_DCRO1IRy1OagODK&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR</value>
      <webElementGuid>3103d1e4-3716-45e9-a0d2-499af3e7a8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>c3d56dca-5d81-4bb8-b8ee-ce3315cab290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Login/iframe_html1body1div5div4iframe1_c-x9j2mliy5o8z</value>
      <webElementGuid>4b9fca32-7154-4466-8be2-c2b640e61e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>2dbe9a07-7fa0-4954-9dd5-e690d86f1b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhxCtW-Se7DGWr83Sfmu0PubP8UHTdl_dIt0loTqwUQMIJDUggfSFvkquMH4TSt3ZFTACbiIagkArZi6CPqoG0AhU68lW4pvBHu8aM3-fmB0K4oIn7gLF7KKi2YhF7TiaT8zjVt2lslQl8-H97oFcTd9x13r1YYzt7CRp-RxKgFuSpDl2b52KwM_DCRO1IRy1OagODK&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR')]</value>
      <webElementGuid>62dcd76e-2304-4466-b765-d7f706e5eff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4ccdfe7f-6f94-4b20-9d65-c13fad77383b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhxCtW-Se7DGWr83Sfmu0PubP8UHTdl_dIt0loTqwUQMIJDUggfSFvkquMH4TSt3ZFTACbiIagkArZi6CPqoG0AhU68lW4pvBHu8aM3-fmB0K4oIn7gLF7KKi2YhF7TiaT8zjVt2lslQl8-H97oFcTd9x13r1YYzt7CRp-RxKgFuSpDl2b52KwM_DCRO1IRy1OagODK&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR']</value>
      <webElementGuid>cb7da424-56d7-419d-adde-b331308dd080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
