<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_staf_lembaga_menengahyopmail.com</name>
   <tag></tag>
   <elementGuidId>57f3bbe6-bd74-4b5e-8604-35e48766baf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kirim-persetujuan-list']/div[2]/div/div/div[5]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ee1a81e-daea-425c-9f24-a15183abf308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>010356c4-b175-4723-99aa-c8c04defa234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-cqee49 r-1b43r93 r-fdjqy7</value>
      <webElementGuid>b48b13fa-daf8-4f84-b85b-13f540ca2b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>staf_lembaga_menengah@yopmail.com</value>
      <webElementGuid>d33684e4-ad6e-4db0-96a6-5f8d32cbcf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kirim-persetujuan-list&quot;)/div[@class=&quot;css-1dbjc4n r-150rngu r-eqz5dr r-16y2uox r-1wbh5a2 r-11yh6sk r-1rnoaur r-2eszeu r-1sncvnh&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1ftlef7 r-1dzdj1l r-1vxxoco r-6koalj r-1544tr9 r-18u37iz r-ubezar r-1wtj0ep r-135wba7 r-1ifxtd0 r-1qhn6m8 r-1ah4tor&quot;]/div[@class=&quot;css-1dbjc4n r-1habvwh r-6koalj r-13awgt0 r-eqz5dr r-1h0z5md r-tvv088 r-1rozpwm&quot;]/div[@class=&quot;css-901oao r-cqee49 r-1b43r93 r-fdjqy7&quot;]</value>
      <webElementGuid>46e3adfc-a0d1-41b0-92de-02b56d99b939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kirim-persetujuan-list']/div[2]/div/div/div[5]/div[2]</value>
      <webElementGuid>8ca793b8-5954-46c0-b129-ee0794387b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMAIL'])[1]/following::div[1]</value>
      <webElementGuid>5f58f449-d2f6-454c-b785-cef979b57f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK'])[1]/following::div[4]</value>
      <webElementGuid>9cc67c84-bbe8-4237-ad17-fc63a8ac98ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SURAT TUGAS'])[1]/preceding::div[1]</value>
      <webElementGuid>1c13ff51-6a56-45bb-b41a-a47e9e80c7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIHAT SURAT'])[1]/preceding::div[4]</value>
      <webElementGuid>99123d1c-1443-402c-a716-241556d54b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='staf_lembaga_menengah@yopmail.com']/parent::*</value>
      <webElementGuid>90e48e11-38b7-4df4-8c9a-7771f7dca64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div[5]/div[2]</value>
      <webElementGuid>9ef4a462-94be-49db-b6de-37cc95bc5fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'staf_lembaga_menengah@yopmail.com' or . = 'staf_lembaga_menengah@yopmail.com')]</value>
      <webElementGuid>e6906cda-9f19-406e-9973-373eb2313203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
