<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__css-11aywtz r-1pz39u2 r-cqee49 r-13a_ee316b</name>
   <tag></tag>
   <elementGuidId>17682d09-3625-4732-b6c1-1854f3ec7906</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-11aywtz.r-1pz39u2.r-cqee49.r-13awgt0.r-1b43r93.r-16dba41.r-bcqeeo.r-1m04atk.r-1qzd3f0.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33f3a601-fa8f-4b88-9042-91b0a42585a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Bidang/Nama/Email</value>
      <webElementGuid>b3008afe-7fe3-4299-a66b-f27c54c151d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>b84f265c-2d5a-4c61-b6bc-146b8cacee84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e09914c3-ceab-494e-b25c-64766d772360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a62d6e08-b896-4c93-a8f5-9c923f05aa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2fe70867-1efa-471d-87cc-c618b514e5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enterkeyhint</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>743b5d0a-136c-4c81-b125-4420eef5ee83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e004c1c-1342-4ada-a394-1483adc7f189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6cfa7b7-5b35-4cb2-a9e1-9214161e277d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>82fdfdd4-34c4-401e-b395-9eb6c43992c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11aywtz r-1pz39u2 r-cqee49 r-13awgt0 r-1b43r93 r-16dba41 r-bcqeeo r-1m04atk r-1qzd3f0 r-fdjqy7</value>
      <webElementGuid>d8d54f16-3f77-4b7d-9e8b-af828d2c4a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cfbf9ab9-0367-4fe9-93c2-692e0ee95253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kirim-persetujuan-list&quot;)/div[@class=&quot;css-1dbjc4n r-18u37iz r-1wtj0ep&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-14lw9ot r-18u37iz&quot;]/input[@class=&quot;css-11aywtz r-1pz39u2 r-cqee49 r-13awgt0 r-1b43r93 r-16dba41 r-bcqeeo r-1m04atk r-1qzd3f0 r-fdjqy7&quot;]</value>
      <webElementGuid>1604b088-5c90-4bb0-a386-b648eff7bc30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>a8cd6b08-4f0f-4129-939a-bb6a943abf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kirim-persetujuan-list']/div/div[2]/div/input</value>
      <webElementGuid>cb79d10a-6f17-4d52-90ff-b893f9db94bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d116caf-77bc-4e0f-9b21-f347e07b23e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari Bidang/Nama/Email' and @type = 'text']</value>
      <webElementGuid>703dcf56-7a45-4bbb-ad2c-ce731507641f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
