<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>12145137-b5ff-4734-b41a-c29db7514188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.css-901oao.css-16my406.r-adyw6z</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kirim-persetujuan-list']/div[2]/div/div/div[7]/div/div/div/div/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26e85986-ebed-4e54-b542-0350954b51c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao css-16my406 r-adyw6z</value>
      <webElementGuid>0ec47cd3-92c6-46c2-90d6-9463e524afbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>󰍝</value>
      <webElementGuid>d952cdec-5e60-40d4-928a-d5228716e6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kirim-persetujuan-list&quot;)/div[@class=&quot;css-1dbjc4n r-150rngu r-eqz5dr r-16y2uox r-1wbh5a2 r-11yh6sk r-1rnoaur r-2eszeu r-1sncvnh&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1ftlef7 r-1dzdj1l r-1vxxoco r-6koalj r-1544tr9 r-18u37iz r-ubezar r-1wtj0ep r-135wba7 r-1ifxtd0 r-1qhn6m8 r-1ah4tor&quot;]/div[@class=&quot;css-1dbjc4n r-1kihuf0&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-18t94o4 css-1dbjc4n r-1loqt21 r-1udh08x r-bnwqim&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-1777fci&quot;]/div[@class=&quot;css-901oao css-bfa6kz r-ud0q2t r-1ydw1k6 r-712mwr r-q4m81j r-tsynxw r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-xoduu5 r-18u37iz r-1wtj0ep&quot;]/span[@class=&quot;css-901oao css-16my406 r-adyw6z&quot;]</value>
      <webElementGuid>08daed4d-8bd2-49d8-b119-324fbf51f872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kirim-persetujuan-list']/div[2]/div/div/div[7]/div/div/div/div/div/div/span[2]</value>
      <webElementGuid>756fbf29-103a-4e6d-903d-9af0ee9a38e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[2]/following::span[1]</value>
      <webElementGuid>a0e19461-f4fa-43f6-9eb1-e5e988c81018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UMUR PENGAJUAN'])[1]/following::span[2]</value>
      <webElementGuid>efaf479c-4b21-42ea-a55b-f25b37e10de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/preceding::span[3]</value>
      <webElementGuid>ddfae10b-dbd7-4526-bdd5-d56a82fc958e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::span[3]</value>
      <webElementGuid>12b973ce-6166-43ae-8b41-e32745b3c5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='󰍝']/parent::*</value>
      <webElementGuid>2713e0e9-0d52-4a61-85d2-f807a9217e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/span[2]</value>
      <webElementGuid>73e7ab7b-1f7d-4d12-9b58-6f4fbff7719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '󰍝' or . = '󰍝')]</value>
      <webElementGuid>6568f822-5e8b-4be6-a0aa-94b1aba8e1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
