<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div5div4iframe1_c-jsm0wpr2w43d</name>
   <tag></tag>
   <elementGuidId>56eae8cc-f497-4aa0-9841-14d222867092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-jsm0wpr2w43d&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-jsm0wpr2w43d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5869eaff-161b-40e7-8f74-095b614ba2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>masa berlaku tantangan recaptcha akan berakhir dalam dua menit</value>
      <webElementGuid>1b87d491-07c0-40c8-8076-370f13fa687a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=zmiYzsHi8INTJBWt2QZC9aM5&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR</value>
      <webElementGuid>0bbf9826-a187-4076-bc44-19898b4296b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-jsm0wpr2w43d</value>
      <webElementGuid>ceb41b41-d01f-4a39-89da-1a7d54319ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0727694-6105-4540-90b8-081205102711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>913b8830-988e-4542-973e-96d13ab4747a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>50a3ad61-2f5e-49fd-8441-231b5b4cb528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19dfb51e-ac64-4320-8497-aab3f4ec4900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[5]/div[4]/iframe[1]</value>
      <webElementGuid>ad066a60-10fe-48c1-8e1b-f75863f7952f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-jsm0wpr2w43d']</value>
      <webElementGuid>88df04f7-1d3b-407b-ba43-cf96e898cca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>97788f1f-dcd5-4bee-877e-6c08dff3e79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'masa berlaku tantangan recaptcha akan berakhir dalam dua menit' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=zmiYzsHi8INTJBWt2QZC9aM5&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR' and @name = 'c-jsm0wpr2w43d']</value>
      <webElementGuid>f52d5b90-977c-44f5-b4c2-0171df59acf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
