<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lampu lalu lintas_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>4f0feaf7-6474-4d8e-ab9f-c499066a581b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e147618d-e738-4ad1-9065-91502230c584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>3b9823c5-0e56-4dc7-83fd-7ddee62d8d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukzgOW_ibIM6kg_fN4xL9c5AyD7P0f3FVSri2b5gCIXOuD8CVCbun7u_RrdxQ9C7drxVwiynyd7Sy_VagI4yf2v49jTgRwAK8eBue4Yb_7UQqVOyZStcso3FL9plErRkrryEYKCrW8IUFiihG9ZoaBXAfLxavut6W02iauY-ZkXecMh6cOSDXb1Nr0RhuXG9WhqM_NDZq&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR</value>
      <webElementGuid>7c2eb736-facf-4919-999d-253fe8967087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>4de9d325-8014-4fcf-ac98-37575b12662f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Siswa Kemenag/Page_Login/iframe_html1body1div5div4iframe1_c-jsm0wpr2w43d</value>
      <webElementGuid>e23302da-6820-497b-85c4-3e9ee2f44f9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>07ad332e-6a82-489e-8d15-5ddbf51bd65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukzgOW_ibIM6kg_fN4xL9c5AyD7P0f3FVSri2b5gCIXOuD8CVCbun7u_RrdxQ9C7drxVwiynyd7Sy_VagI4yf2v49jTgRwAK8eBue4Yb_7UQqVOyZStcso3FL9plErRkrryEYKCrW8IUFiihG9ZoaBXAfLxavut6W02iauY-ZkXecMh6cOSDXb1Nr0RhuXG9WhqM_NDZq&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR')]</value>
      <webElementGuid>e66ccb41-6832-4762-bf6a-43682ccb3467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b1ec20ac-eb0e-4589-bfa8-bd7ca2bfc7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukzgOW_ibIM6kg_fN4xL9c5AyD7P0f3FVSri2b5gCIXOuD8CVCbun7u_RrdxQ9C7drxVwiynyd7Sy_VagI4yf2v49jTgRwAK8eBue4Yb_7UQqVOyZStcso3FL9plErRkrryEYKCrW8IUFiihG9ZoaBXAfLxavut6W02iauY-ZkXecMh6cOSDXb1Nr0RhuXG9WhqM_NDZq&amp;k=6LfbiegZAAAAAHQtVhER7vn0GMD7CBEMRSN-6YbR']</value>
      <webElementGuid>596e5f94-16a4-4764-bf85-d4afbae75ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
